# Generated by Django 5.2.4 on 2025-09-07 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mood',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mood',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mood',
            name='color',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='mood',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='note',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='user',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
