# Generated by Django 5.2.4 on 2025-09-09 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_mood_unique_together_mood_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mood',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='diary.mood'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_record_user_date'),
        ),
        migrations.RemoveField(
            model_name='record',
            name='title',
        ),
    ]
